name: KPS8x9M2gamePlugin
version: ${project.version}
main: jp.kps8x9.middle2.kps8x9m2gameplugin.KPS8x9M2gamePlugin
api-version: 1.13
commands:
  m2test:
    description: M2Test
    usage: /m2test
<<<<<<< HEAD
  start:
    description: 開始

permissions:
  itazura:
    default: op

=======
  finish:
    usge: /finish
  mh:
    description: MH_command
    usage: /mh
>>>>>>> d5a5260e9955cc038eae1db15310efe06a2474d9
